spring.application.name=springboot-bootcamp

spring.profiles.active=prd

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Puerto dinámico que asigna Railway
server.port=${PORT:8080}




