spring.application.name=springboot_bootcamp
spring.datasource.url=jdbc:postgresql://localhost:5432/angie
spring.datasource.username=postgres
spring.datasource.password=v13522957-8
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update 
spring.security.debug=true


